language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install: pip install -r requirements.txt
script:
  - python -Wall -m unittest discover -t . -s rouver_test -p "*.py"
  - mypy rouver rouver_test
  - flake8
